wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: fastai
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.6
    start_time: 1674661497.046732
    t:
      1:
      - 1
      - 4
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 4
      - 5
      - 41
      - 53
      - 55
      3:
      - 23
      4: 3.10.6
      5: 0.13.9
      8:
      - 1
      - 5
